<!-- ============================================
     IP Address Section (Pool-based, same as Register)
     Modes: Add IP / Remove IP / Change IP
============================================= -->

<!-- Old IPs (read-only, populated by import) -->
<div class="grid">
    <div class="col">
        <div class="row">
            <div class="label">Current IPs</div><div class="colon">:</div>
            <div class="control">
                <div id="rc-old-ip-list" style="color:#666; font-style:italic;">No customer imported yet.</div>
            </div>
        </div>
    </div>

    <!-- ===== ADD IP Section ===== -->
    <span id="rc-new-ip-section" style="display:none;">
        <div class="col">
            <div class="row">
                <div class="label" id="rc-new-ip-label">New IPs</div><div class="colon">:</div>
                <div class="control ip-control">
                    <input type="number" id="rc-ip-quantity" min="0" value="0" readonly>
                    <button type="button" class="qty-btn plus" id="rc-add-ip-btn">+</button>
                </div>
            </div>

            <div id="rc-ip-rows-container">
                <!-- Dynamic rows added here -->
            </div>

            <div id="rc-ip-duplicate-msg" style="color:#dc2626; font-size:13px; margin-top:6px; display:none;">
                Duplicate IP detected. Please make all IPs unique.
            </div>
        </div>
    </span>

    <!-- ===== REMOVE IP Section ===== -->
    <span id="rc-remove-ip-section" style="display:none;">
        <div class="col">
            <div class="row">
                <div class="label">Select IPs to Remove</div><div class="colon">:</div>
                <div class="control">
                    <div id="rc-remove-ip-list">
                        <!-- Checkboxes generated by JS -->
                    </div>
                </div>
            </div>
        </div>
    </span>

    <!-- ===== CHANGE IP Section (per-IP select & update) ===== -->
    <span id="rc-change-ip-section" style="display:none;">
        <div class="col">
            <div class="row">
                <div class="label">Select IPs to Change</div><div class="colon">:</div>
                <div class="control" style="flex-direction:column; align-items:stretch;">
                    <div id="rc-change-ip-list">
                        <!-- Checkboxes + replacement rows generated by JS -->
                    </div>
                    <div id="rc-change-ip-duplicate-msg" style="color:#dc2626; font-size:13px; margin-top:6px; display:none;">
                        Duplicate replacement IP detected. Please make all IPs unique.
                    </div>
                </div>
            </div>
        </div>
    </span>
</div>


<!-- Hidden fields -->
<input type="hidden" name="old_ip_ids" id="rc-old-ip-ids" value="">
<input type="hidden" name="remove_ids" id="rc-remove-ids" value="">

<!-- Pool / free IP data from server -->
<script id="rc-free-by-pool-data" type="application/json">
    @json($freeByPool ?? [])
</script>

<!-- IP row template (same as register) -->
<template id="rc-ip-row-template">
    <div class="row ip-row" style="margin-bottom: 5px">
        <select class="pool-select label" style="margin-top: 0px">
            <option value="">Select Pool</option>
            @foreach ($pools ?? [] as $pool)
                <option value="{{ $pool->id }}">{{ $pool->name }}</option>
            @endforeach
        </select>

        <div class="control">
            <select class="ip-input" name="" required>
                <option value="">Select IP</option>
            </select>
            <input type="text" class="ip-note" name="" placeholder="note">
            <button type="button" class="qty-btn minus">-</button>
        </div>
    </div>
</template>

<!-- ✅ Self-contained IP Module Script -->
<script>
(function () {
    document.addEventListener('DOMContentLoaded', function () {

        const container    = document.getElementById('rc-ip-rows-container');
        const template     = document.getElementById('rc-ip-row-template');
        const qtyInput     = document.getElementById('rc-ip-quantity');
        const addBtn       = document.getElementById('rc-add-ip-btn');
        const dupMsg       = document.getElementById('rc-ip-duplicate-msg');
        const oldIpList    = document.getElementById('rc-old-ip-list');
        const newSection   = document.getElementById('rc-new-ip-section');
        const removeSection = document.getElementById('rc-remove-ip-section');
        const changeSection = document.getElementById('rc-change-ip-section');
        const removeList   = document.getElementById('rc-remove-ip-list');
        const changeList   = document.getElementById('rc-change-ip-list');
        const changeDupMsg = document.getElementById('rc-change-ip-duplicate-msg');
        const oldIpIdsInput = document.getElementById('rc-old-ip-ids');
        const removeIdsInput = document.getElementById('rc-remove-ids');
        const newIpLabel   = document.getElementById('rc-new-ip-label');

        // Pool options HTML (reused in change rows)
        const poolOptionsHtml = template.content.querySelector('.pool-select').innerHTML;

        // Load free IPs by pool
        const freeByPool = JSON.parse(
            document.getElementById('rc-free-by-pool-data').textContent
        );

        let currentCustomer = null;
        let currentMode = null; // 'add', 'remove', 'change', or null

        /* =========================
            UTILITY
        ========================== */
        function markInvalid(input) { input.style.borderColor = '#dc2626'; }
        function clearInvalid(input) { input.style.borderColor = ''; }

        function updateQuantity() {
            qtyInput.value = container.querySelectorAll('.ip-row').length;
        }

        function reindexRows() {
            container.querySelectorAll('.ip-row').forEach((row, i) => {
                const ipSelect = row.querySelector('.ip-input');
                const noteInput = row.querySelector('.ip-note');
                if (ipSelect) ipSelect.name = `ip_items[${i}][id]`;
                if (noteInput) noteInput.name = `ip_items[${i}][note]`;
            });
        }

        function getSelectedIps() {
            return Array.from(container.querySelectorAll('.ip-input'))
                .map(s => s.value)
                .filter(v => v);
        }

        function getSelectedChangeIps() {
            return Array.from(changeList.querySelectorAll('.change-ip-select'))
                .map(s => s.value)
                .filter(v => v);
        }

        function populateIpSelect(ipSelect, poolId, currentValue, excludeList) {
            ipSelect.innerHTML = '<option value="">Select IP</option>';
            if (!poolId || !freeByPool[poolId]) return;

            const usedIps = excludeList || getSelectedIps();

            freeByPool[poolId].forEach(item => {
                if (item.id == currentValue || !usedIps.includes(String(item.id))) {
                    const opt = document.createElement('option');
                    opt.value = item.id;
                    opt.textContent = item.ip;
                    if (item.id == currentValue) opt.selected = true;
                    ipSelect.appendChild(opt);
                }
            });
        }

        function populateChangeIpSelect(ipSelect, poolId, currentValue) {
            ipSelect.innerHTML = '<option value="">Select New IP</option>';
            if (!poolId || !freeByPool[poolId]) return;

            const usedIps = getSelectedChangeIps();

            freeByPool[poolId].forEach(item => {
                if (item.id == currentValue || !usedIps.includes(String(item.id))) {
                    const opt = document.createElement('option');
                    opt.value = item.id;
                    opt.textContent = item.ip;
                    if (item.id == currentValue) opt.selected = true;
                    ipSelect.appendChild(opt);
                }
            });
        }

        /* =========================
            ADD ROW (for Add IP mode)
        ========================== */
        function addRow(value = '') {
            const clone = template.content.cloneNode(true);
            const input = clone.querySelector('.ip-input');
            input.value = value;
            container.appendChild(clone);
            reindexRows();
            updateQuantity();
        }

        /* =========================
            DUPLICATE CHECK (Add IP)
        ========================== */
        function validateDuplicateIPs() {
            const inputs = Array.from(container.querySelectorAll('.ip-input'));
            inputs.forEach(clearInvalid);
            dupMsg.style.display = 'none';

            const map = new Map();
            inputs.forEach(input => {
                const value = input.value.trim();
                if (!value) return;
                if (!map.has(value)) map.set(value, []);
                map.get(value).push(input);
            });

            let hasDuplicate = false;
            map.forEach(arr => {
                if (arr.length > 1) {
                    hasDuplicate = true;
                    arr.forEach(markInvalid);
                }
            });

            dupMsg.style.display = hasDuplicate ? 'block' : 'none';
            return !hasDuplicate;
        }

        /* =========================
            DUPLICATE CHECK (Change IP)
        ========================== */
        function validateChangeDuplicateIPs() {
            const inputs = Array.from(changeList.querySelectorAll('.change-ip-select'));
            inputs.forEach(clearInvalid);
            changeDupMsg.style.display = 'none';

            const map = new Map();
            inputs.forEach(input => {
                const value = input.value.trim();
                if (!value) return;
                if (!map.has(value)) map.set(value, []);
                map.get(value).push(input);
            });

            let hasDuplicate = false;
            map.forEach(arr => {
                if (arr.length > 1) {
                    hasDuplicate = true;
                    arr.forEach(markInvalid);
                }
            });

            changeDupMsg.style.display = hasDuplicate ? 'block' : 'none';
            return !hasDuplicate;
        }

        /* =========================
            EVENTS ON CONTAINER (Add IP)
        ========================== */
        container.addEventListener('change', function (e) {
            if (e.target.classList.contains('pool-select')) {
                const row = e.target.closest('.ip-row');
                const ipSelect = row.querySelector('.ip-input');
                populateIpSelect(ipSelect, e.target.value, '');
            }
            if (e.target.classList.contains('ip-input')) {
                validateDuplicateIPs();
            }
        });

        container.addEventListener('click', function (e) {
            if (e.target.classList.contains('minus')) {
                e.target.closest('.ip-row').remove();
                reindexRows();
                validateDuplicateIPs();
                updateQuantity();
            }
        });

        if (addBtn) {
            addBtn.addEventListener('click', () => addRow(''));
        }

        /* =========================
            REMOVE CHECKBOXES
        ========================== */
        function buildRemoveCheckboxes(ips) {
            removeList.innerHTML = '';
            ips.forEach(ip => {
                const label = document.createElement('label');
                label.style.cssText = 'display:flex; align-items:center; gap:8px; margin-bottom:6px; cursor:pointer;';

                const cb = document.createElement('input');
                cb.type = 'checkbox';
                cb.value = ip.id;
                cb.dataset.ipAddress = ip.ip_address;
                cb.addEventListener('change', updateRemoveIds);

                const span = document.createElement('span');
                span.textContent = ip.ip_address;

                label.appendChild(cb);
                label.appendChild(span);
                removeList.appendChild(label);
            });
        }

        function updateRemoveIds() {
            const checked = Array.from(removeList.querySelectorAll('input[type="checkbox"]:checked'));
            removeIdsInput.value = checked.map(cb => cb.value).join(',');
        }

        /* =========================
            ✅ CHANGE IP: Checkboxes + Replacement Rows
        ========================== */
        function buildChangeCheckboxes(ips) {
            changeList.innerHTML = '';
            ips.forEach((ip, index) => {
                // Wrapper for this IP entry
                const wrapper = document.createElement('div');
                wrapper.className = 'rc-change-item';
                wrapper.dataset.oldIpId = ip.id;

                // Checkbox row
                const label = document.createElement('label');
                label.className = 'rc-change-label';

                const cb = document.createElement('input');
                cb.type = 'checkbox';
                cb.value = ip.id;
                cb.dataset.ipAddress = ip.ip_address;
                cb.dataset.index = index;
                cb.addEventListener('change', function () {
                    toggleChangeRow(wrapper, cb, index);
                });

                const span = document.createElement('span');
                span.textContent = ip.ip_address;

                label.appendChild(cb);
                label.appendChild(span);
                wrapper.appendChild(label);

                changeList.appendChild(wrapper);
            });
        }

        function toggleChangeRow(wrapper, checkbox, index) {
            const existing = wrapper.querySelector('.rc-change-replacement');

            if (checkbox.checked) {
                if (!existing) {
                    // Build replacement row using the same design system
                    const row = document.createElement('div');
                    row.className = 'rc-change-replacement row ip-row';

                    // Pool select (reuse same pool options from template)
                    const poolSelect = document.createElement('select');
                    poolSelect.className = 'pool-select label';
                    poolSelect.innerHTML = poolOptionsHtml;

                    // Control wrapper
                    const control = document.createElement('div');
                    control.className = 'control';

                    // IP select
                    const ipSelect = document.createElement('select');
                    ipSelect.className = 'change-ip-select';
                    ipSelect.name = `change_items[${index}][new_id]`;
                    ipSelect.required = true;
                    ipSelect.innerHTML = '<option value="">-- Select New IP --</option>';

                    // Note input
                    const noteInput = document.createElement('input');
                    noteInput.type = 'text';
                    noteInput.className = 'change-ip-note';
                    noteInput.name = `change_items[${index}][note]`;
                    noteInput.placeholder = 'note';

                    // Hidden old_id
                    const oldIdInput = document.createElement('input');
                    oldIdInput.type = 'hidden';
                    oldIdInput.name = `change_items[${index}][old_id]`;
                    oldIdInput.value = checkbox.value;

                    // Pool change → populate IPs
                    poolSelect.addEventListener('change', function () {
                        populateChangeIpSelect(ipSelect, poolSelect.value, '');
                    });

                    // IP change → validate duplicates
                    ipSelect.addEventListener('change', function () {
                        validateChangeDuplicateIPs();
                    });

                    control.appendChild(ipSelect);
                    control.appendChild(noteInput);

                    row.appendChild(poolSelect);
                    row.appendChild(control);
                    row.appendChild(oldIdInput);
                    wrapper.appendChild(row);
                }
            } else {
                if (existing) {
                    existing.remove();
                    // Also remove hidden input if outside
                    const hiddenInput = wrapper.querySelector('input[type="hidden"]');
                    if (hiddenInput) hiddenInput.remove();
                    validateChangeDuplicateIPs();
                }
            }

            reindexChangeItems();
        }

        function reindexChangeItems() {
            const wrappers = changeList.querySelectorAll('.rc-change-item');
            let idx = 0;
            wrappers.forEach(wrapper => {
                const cb = wrapper.querySelector('input[type="checkbox"]');
                const row = wrapper.querySelector('.rc-change-replacement');
                if (cb && cb.checked && row) {
                    const ipSelect = row.querySelector('.change-ip-select');
                    const noteInput = row.querySelector('.change-ip-note');
                    const oldIdInput = wrapper.querySelector('input[type="hidden"]');
                    if (ipSelect) ipSelect.name = `change_items[${idx}][new_id]`;
                    if (noteInput) noteInput.name = `change_items[${idx}][note]`;
                    if (oldIdInput) oldIdInput.name = `change_items[${idx}][old_id]`;
                    idx++;
                }
            });
        }

        /* =========================
            RENDER OLD IPS LIST
        ========================== */
        function renderOldIps(ips) {
            if (!ips || ips.length === 0) {
                oldIpList.innerHTML = '<span style="color:#999;">No IPs assigned to this customer.</span>';
                oldIpIdsInput.value = '';
                return;
            }

            oldIpIdsInput.value = ips.map(ip => ip.id).join(',');

            const list = document.createElement('div');
            ips.forEach(ip => {
                const item = document.createElement('div');
                item.style.cssText = 'padding:3px 0; font-size:14px;';
                item.textContent = `• ${ip.ip_address}`;
                list.appendChild(item);
            });
            oldIpList.innerHTML = '';
            oldIpList.appendChild(list);
        }

        /* =========================
            MODE SWITCHING
        ========================== */
        function setMode(mode) {
            currentMode = mode;

            // Hide all sections first
            newSection.style.display = 'none';
            removeSection.style.display = 'none';
            changeSection.style.display = 'none';

            // Clear containers
            container.innerHTML = '';
            removeList.innerHTML = '';
            changeList.innerHTML = '';
            removeIdsInput.value = '';
            changeDupMsg.style.display = 'none';
            updateQuantity();

            if (mode === 'add') {
                newIpLabel.textContent = 'New IPs to Add';
                newSection.style.display = 'block';
                addRow(''); // Start with one empty row
            } else if (mode === 'remove') {
                removeSection.style.display = 'block';
                if (currentCustomer && currentCustomer.old_ip_addresses) {
                    buildRemoveCheckboxes(currentCustomer.old_ip_addresses);
                }
            } else if (mode === 'change') {
                changeSection.style.display = 'block';
                if (currentCustomer && currentCustomer.old_ip_addresses) {
                    buildChangeCheckboxes(currentCustomer.old_ip_addresses);
                }
            }
        }

        /* =========================
            PUBLIC API (window.RequestChangeIP)
        ========================== */
        window.RequestChangeIP = {

            setCustomer(customer) {
                currentCustomer = customer;
                renderOldIps(customer.old_ip_addresses || []);

                // Re-render mode if already selected
                if (currentMode) {
                    setMode(currentMode);
                }
            },

            onRequestTypeChange({ requestType, customer }) {
                if (requestType === 'Add IP Address') {
                    setMode('add');
                } else if (requestType === 'Remove IP Address') {
                    setMode('remove');
                } else if (requestType === 'Change IP Address') {
                    setMode('change');
                } else {
                    setMode(null);
                }
            },

            reset() {
                currentCustomer = null;
                currentMode = null;
                container.innerHTML = '';
                removeList.innerHTML = '';
                changeList.innerHTML = '';
                oldIpList.innerHTML = '<span style="color:#666; font-style:italic;">No customer imported yet.</span>';
                oldIpIdsInput.value = '';
                removeIdsInput.value = '';
                newSection.style.display = 'none';
                removeSection.style.display = 'none';
                changeSection.style.display = 'none';
                changeDupMsg.style.display = 'none';
                updateQuantity();
            }
        };
    });
})();
</script>

<style>
    /* Change IP item: checkbox + IP address */
    .rc-change-item {
        margin-bottom: 8px;
    }

    .rc-change-label {
        display: flex;
        align-items: center;
        gap: 8px;
        cursor: pointer;
        font-size: 14px;
    }

    .rc-change-label input[type="checkbox"] {
        width: 15px;
        height: 15px;
        cursor: pointer;
    }

    /* Replacement row: styled like the ip-row in Add IP */
    .rc-change-replacement {
        margin-top: 5px;
        margin-left: 23px;
    }

    /* Remove padding/margin from pool select in change IP rows */
    .rc-change-replacement .pool-select {
        padding: 0;
        margin: 0;
    }
</style>
